version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - 2181
    hostname: "zookeeper"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    expose:
      - 9092
    hostname: "kafka"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  recepcao_nfe:
    image: recepcao_nfe
    build: .  
    depends_on:
      - kafka
    ports:
      - "5001:5000"
    hostname: "recepcao_nfe"
    volumes:
      - "./servicos/recepcao_nfe:/workdir"
    command: python3 /workdir/servico.py

  verificar_cnpj_emitente:
    image: verificar_cnpj_emitente
    build: .
    depends_on:
      - kafka
    hostname: "verificar_cnpj_emitente"
    volumes:
      - "./servicos/verificar_cnpj_emitente:/workdir"
    command: python3 /workdir/servico.py

  recepcao_nfe_ambiente_nacional:
    image: recepcao_nfe_ambiente_nacional
    build: .
    depends_on:
      - kafka
    hostname: "recepcao_nfe_ambiente_nacional"
    volumes:
      - "./servicos/recepcao_nfe_ambiente_nacional:/workdir"
    command: python3 /workdir/servico.py

  envio_de_email:
    image: envio_de_email
    build: .
    depends_on:
      - kafka
    hostname: "envio_de_email"
    volumes:
      - "./servicos/envio_de_email:/workdir"
    command: python3 /workdir/servico.py
